- name: Deploy Sample App Container
  hosts: localhost
  become: true
  tasks:
    - name: Free up port 80 if in use
      shell: |
        fuser -k 80/tcp || true

    - name: Remove existing container (if any)
      shell: docker rm -f sample-app || true

    - name: Run new container (Port 80 -> 5000)
      shell: docker run -d --name sample-app -p 80:5000 sample-app
