- name: Deploy Sample App Container
  hosts: localhost
  become: true
  tasks:
    - name: Stop and remove existing container
      shell: docker rm -f sample-app || true

    - name: Run local image as container
      shell: docker run -d --name sample-app -p 80:8080 sample-app
